[package]
name = "rocky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.23.3", features = ["yaml"] }
nom = "4.2.3"
log = "0.4.17"
env_logger = "0.5.13"
byteorder = "1.4.3"